version: '3.9'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/api
      - gem-store:/usr/local/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
    depends_on:
      - psql
    stdin_open: true
    tty: true
  psql:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./db/psql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --local=ja_JP.UTF-8'
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/client:cached
      - node_modules:/client/node_modules
    ports:
      - '8080:5173'
    depends_on:
      - api
    tty: true
    command: yarn dev --host
volumes:
  db-data:
  gem-store:
  node_modules: